name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      nats:
        image: nats:latest
        ports:
          - 4222:4222
          - 8222:8222
        options: >-
          --health-cmd "wget -qO- http://127.0.0.1:8222/healthz || exit 1"
          --health-interval 2s
          --health-timeout 2s
          --health-retries 30
          -js
          -m 8222 


    env:
      NATASKS_NATS_URL: nats://127.0.0.1:4222

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test -v ./...

